# Generated by Django 3.1 on 2020-08-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_info',
            old_name='ClientName',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='ClientNameCHT',
            new_name='clientNameCHT',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='ClientNameEN',
            new_name='clientNameEN',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='ClientNameJP',
            new_name='clientNameJP',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='SerialNo',
            new_name='serialNo',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='ShowClientName',
            new_name='showClientName',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='Status',
            new_name='status',
        ),
        migrations.CreateModel(
            name='Client_product',
            fields=[
                ('serialNo', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('showProductName', models.CharField(max_length=50)),
                ('unitPrice', models.FloatField()),
                ('industryType', models.CharField(max_length=50)),
                ('productType', models.CharField(max_length=50)),
                ('hashTag', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('clientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_clientName', to='client.client_info')),
            ],
        ),
    ]
