# Generated by Django 3.1 on 2020-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200818_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_product',
            name='hashTag',
            field=models.CharField(max_length=150),
        ),
    ]
