# Generated by Django 3.1 on 2020-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200818_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='clientName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='clientNameCHT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='clientNameEN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='clientNameJP',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='showClientName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_product',
            name='productName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_product',
            name='showProductName',
            field=models.CharField(max_length=100),
        ),
    ]
