# Generated by Django 3.1 on 2020-08-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientInfo',
        ),
        migrations.DeleteModel(
            name='ClientProduct',
        ),
    ]
