# Generated by Django 3.1 on 2020-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_clientinfo_clientproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'v_client',
                'managed': False,
            },
        ),
    ]
