# Generated by Django 3.0.9 on 2020-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_crosweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosOrder',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('order_id', models.TextField(blank=True, db_column='Order_ID', null=True)),
                ('customer_id', models.TextField(blank=True, db_column='Customer_ID', null=True)),
                ('order_status', models.TextField(blank=True, db_column='Order_Status', null=True)),
                ('order_price', models.IntegerField(blank=True, db_column='Order_Price', null=True)),
                ('del_flg', models.TextField(blank=True, null=True)),
                ('pay_method', models.TextField(blank=True, db_column='Pay_Method', null=True)),
                ('pickup_method', models.TextField(blank=True, db_column='Pickup_Method', null=True)),
                ('regular', models.TextField(blank=True, db_column='Regular', null=True)),
                ('regular_times', models.IntegerField(blank=True, db_column='Regular_Times', null=True)),
                ('campaign', models.TextField(blank=True, db_column='Campaign', null=True)),
                ('promotion_code', models.TextField(blank=True, db_column='Promotion_Code', null=True)),
                ('buy_date', models.DateTimeField(blank=True, db_column='Buy_Date', null=True)),
                ('cancel_date', models.DateTimeField(blank=True, db_column='Cancel_Date', null=True)),
                ('transfer_date', models.DateTimeField(blank=True, db_column='Transfer_Date', null=True)),
                ('real_transfer_date', models.DateTimeField(blank=True, db_column='Real_Transfer_Date', null=True)),
                ('booking_return_date', models.DateTimeField(blank=True, db_column='Booking_Return_Date', null=True)),
                ('return_status', models.TextField(blank=True, db_column='Return_Status', null=True)),
                ('return_in_warehouse_date', models.DateTimeField(blank=True, db_column='Return_In_Warehouse_Date', null=True)),
                ('order_type', models.TextField(blank=True, db_column='Order_Type', null=True)),
                ('ga1', models.TextField(blank=True, db_column='GA1', null=True)),
                ('ga2', models.TextField(blank=True, db_column='GA2', null=True)),
                ('ga3', models.TextField(blank=True, db_column='GA3', null=True)),
                ('paypal_transaction_id', models.TextField(blank=True, db_column='PayPal_Transaction_ID', null=True)),
                ('apply_id', models.TextField(blank=True, null=True)),
                ('newoto', models.TextField(blank=True, db_column='NewOTO', null=True)),
                ('cross_sell', models.TextField(blank=True, db_column='Cross_Sell', null=True)),
                ('repeat_click_lp', models.TextField(blank=True, db_column='Repeat_Click_LP', null=True)),
                ('multi_buy_lp', models.TextField(blank=True, db_column='Multi_Buy_LP', null=True)),
                ('order_path', models.TextField(blank=True, db_column='Order_Path', null=True)),
                ('invoice_date', models.DateTimeField(blank=True, db_column='Invoice_Date', null=True)),
                ('birth_month', models.TextField(blank=True, null=True)),
                ('sourcetype', models.CharField(blank=True, db_column='SourceType', max_length=255, null=True)),
                ('sourcesubtype', models.CharField(blank=True, db_column='SourceSubType', max_length=255, null=True)),
                ('clientname', models.CharField(blank=True, db_column='ClientName', max_length=255, null=True)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=255, null=True)),
                ('accountname', models.CharField(blank=True, db_column='AccountName', max_length=255, null=True)),
                ('stadatetime', models.DateTimeField(blank=True, db_column='StaDateTime', null=True)),
                ('media', models.CharField(blank=True, max_length=255, null=True)),
                ('link_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cros_order',
                'managed': False,
            },
        ),
    ]
