# Generated by Django 3.0.9 on 2020-09-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20200914_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.TextField(blank=True, db_column='Ad_ID', null=True)),
                ('stadatetime', models.DateTimeField(blank=True, db_column='StaDateTime', null=True)),
                ('ad_time', models.TextField(blank=True, db_column='Ad_Time', null=True)),
                ('campaign_name', models.TextField(blank=True, db_column='Campaign_Name', null=True)),
                ('ad_group_name', models.TextField(blank=True, db_column='Ad_Group_Name', null=True)),
                ('ad_name', models.TextField(blank=True, db_column='Ad_Name', null=True)),
                ('ad_status', models.TextField(blank=True, db_column='Ad_Status', null=True)),
                ('impressions', models.IntegerField(blank=True, db_column='Impressions', null=True)),
                ('clicks', models.IntegerField(blank=True, db_column='Clicks', null=True)),
                ('cv', models.IntegerField(blank=True, db_column='CV', null=True)),
                ('cost', models.IntegerField(blank=True, db_column='Cost', null=True)),
                ('media', models.CharField(blank=True, db_column='media', max_length=255, null=True)),
                ('group_type', models.CharField(blank=True, db_column='group_type', max_length=255, null=True)),
                ('ad_set_daily_budget', models.IntegerField(blank=True, db_column='Ad_Set_Daily_Budget', null=True)),
                ('link', models.TextField(blank=True, db_column='Link', null=True)),
                ('countries', models.TextField(blank=True, db_column='Countries', null=True)),
                ('cities', models.TextField(blank=True, db_column='Cities', null=True)),
                ('regions', models.TextField(blank=True, db_column='Regions', null=True)),
                ('zi_p', models.TextField(blank=True, db_column='Zip', null=True)),
                ('addresses', models.TextField(blank=True, db_column='Addresses', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('age_min', models.IntegerField(blank=True, db_column='Age_Min', null=True)),
                ('age_max', models.IntegerField(blank=True, db_column='Age_Max', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('body', models.TextField(blank=True, db_column='Body', null=True)),
                ('link_type', models.CharField(blank=True, db_column='link_type', max_length=255, null=True)),
                ('sourceType', models.CharField(blank=True, db_column='SourceType', max_length=255, null=True)),
                ('sourceSubType', models.CharField(blank=True, db_column='SourceSubType', max_length=255, null=True)),
                ('clientName', models.CharField(blank=True, db_column='ClientName', max_length=255, null=True)),
                ('productName', models.CharField(blank=True, db_column='ProductName', max_length=255, null=True)),
                ('accountName', models.CharField(blank=True, db_column='AccountName', max_length=255, null=True)),
                ('ga1', models.TextField(blank=True, db_column='GA1', null=True)),
                ('ga2', models.TextField(blank=True, db_column='GA2', null=True)),
                ('ga3', models.TextField(blank=True, db_column='GA3', null=True)),
            ],
            options={
                'db_table': 'v_facebook',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='V_client',
        ),
    ]
