# Generated by Django 3.0.9 on 2020-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20200921_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_line',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('ad_id', models.TextField(blank=True, db_column='ad_id', null=True)),
                ('stadatetime', models.DateTimeField(blank=True, db_column='StaDateTime', null=True)),
                ('adaccount_name', models.TextField(blank=True, db_column='adaccount_name', null=True)),
                ('adaccount_id', models.TextField(blank=True, db_column='adaccount_id', null=True)),
                ('campaign', models.TextField(blank=True, db_column='campaign_name', null=True)),
                ('campaign_objective', models.TextField(blank=True, db_column='campaign_objective', null=True)),
                ('ad_group_name', models.TextField(blank=True, db_column='adgroup_name', null=True)),
                ('ad_name', models.TextField(blank=True, db_column='ad_name', null=True)),
                ('ad_status', models.TextField(blank=True, db_column='ad_status', null=True)),
                ('impressions', models.IntegerField(blank=True, db_column='impression', null=True)),
                ('viewable_impression', models.IntegerField(blank=True, db_column='viewable_impression', null=True)),
                ('clicks', models.IntegerField(blank=True, db_column='clicks', null=True)),
                ('cv', models.IntegerField(blank=True, db_column='cv', null=True)),
                ('cost', models.IntegerField(blank=True, db_column='cost', null=True)),
                ('currency', models.TextField(blank=True, db_column='currency', null=True)),
                ('add_to_cart', models.IntegerField(blank=True, db_column='add_to_cart', null=True)),
                ('add_to_cart_rate', models.TextField(blank=True, db_column='add_to_cart_rate', null=True)),
                ('cost_per_add_to_cart', models.FloatField(blank=True, db_column='cost_per_add_to_cart', null=True)),
                ('purchase', models.IntegerField(blank=True, db_column='purchase', null=True)),
                ('purchase_rate', models.TextField(blank=True, db_column='purchase_rate', null=True)),
                ('cost_per_purchase', models.FloatField(blank=True, db_column='cost_per_purchase', null=True)),
                ('media', models.CharField(blank=True, db_column='media', max_length=255, null=True)),
                ('group_type', models.CharField(blank=True, db_column='group_type', max_length=255, null=True)),
                ('daily_budget', models.IntegerField(blank=True, db_column='daily_budget', null=True)),
                ('payment_method', models.TextField(blank=True, db_column='payment_method', null=True)),
                ('bid_amount', models.FloatField(blank=True, db_column='bid_amount', null=True)),
                ('image_id', models.TextField(blank=True, db_column='image_id', null=True)),
                ('video_id', models.TextField(blank=True, db_column='video_id', null=True)),
                ('landing_page', models.TextField(blank=True, db_column='landing_page', null=True)),
                ('click_url', models.TextField(blank=True, db_column='click_url', null=True)),
                ('gender', models.TextField(blank=True, db_column='gender', null=True)),
                ('age_min', models.IntegerField(blank=True, db_column='age_min', null=True)),
                ('age_max', models.IntegerField(blank=True, db_column='age_max', null=True)),
                ('title', models.TextField(blank=True, db_column='title', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('link_type', models.CharField(blank=True, db_column='link_type', max_length=255, null=True)),
                ('sourceType', models.CharField(blank=True, db_column='SourceType', max_length=255, null=True)),
                ('sourceSubType', models.CharField(blank=True, db_column='SourceSubType', max_length=255, null=True)),
                ('clientname', models.CharField(blank=True, db_column='ClientName', max_length=255, null=True)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=255, null=True)),
                ('accountname', models.CharField(blank=True, db_column='AccountName', max_length=255, null=True)),
                ('ga1', models.TextField(blank=True, db_column='GA1', null=True)),
                ('ga2', models.TextField(blank=True, db_column='GA2', null=True)),
                ('ga3', models.TextField(blank=True, db_column='GA3', null=True)),
            ],
            options={
                'db_table': 'v_line',
                'managed': False,
            },
        ),
    ]
