# Generated by Django 3.1.3 on 2020-11-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_v_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbUniversal',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('ad_id', models.CharField(max_length=25)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('clientname', models.CharField(db_column='ClientName', max_length=30)),
                ('productname', models.CharField(db_column='ProductName', max_length=100)),
                ('accountname', models.CharField(db_column='AccountName', max_length=100)),
                ('industrytype', models.CharField(db_column='IndustryType', max_length=10)),
                ('stadatetime', models.DateTimeField(db_column='StaDateTime')),
                ('group_type', models.CharField(max_length=5)),
                ('campaign_id', models.CharField(max_length=25)),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_status', models.CharField(max_length=10)),
                ('campaign_objective', models.CharField(max_length=25)),
                ('buying_type', models.CharField(max_length=15)),
                ('campaign_daily_budget', models.IntegerField()),
                ('ad_set_id', models.CharField(max_length=25)),
                ('ad_set_run_status', models.CharField(max_length=10)),
                ('ad_set_name', models.CharField(max_length=100)),
                ('ad_set_daily_budget', models.IntegerField()),
                ('link', models.TextField()),
                ('gender', models.CharField(max_length=7)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('publisher_platforms', models.CharField(max_length=255)),
                ('facebook_positions', models.CharField(max_length=255)),
                ('instagram_positions', models.CharField(max_length=255)),
                ('audience_network_positions', models.CharField(max_length=255)),
                ('messenger_positions', models.CharField(max_length=255)),
                ('device_platforms', models.CharField(max_length=30)),
                ('optimization_goal', models.CharField(max_length=30)),
                ('bid_amount', models.IntegerField()),
                ('ad_status', models.CharField(max_length=10)),
                ('ad_name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('link_type', models.CharField(max_length=7)),
                ('ga1', models.TextField()),
                ('ga2', models.TextField()),
                ('ga3', models.TextField()),
            ],
            options={
                'db_table': 'fb_universal',
                'managed': False,
            },
        ),
    ]
