# Generated by Django 3.1.3 on 2020-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_fbuniversal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fbtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ad_id', models.CharField(max_length=25)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('clientname', models.CharField(db_column='ClientName', max_length=30)),
                ('productname', models.CharField(db_column='ProductName', max_length=100)),
                ('accountname', models.CharField(db_column='AccountName', max_length=100)),
                ('industrytype', models.CharField(db_column='IndustryType', max_length=10)),
                ('stadatetime', models.DateTimeField(db_column='StaDateTime')),
                ('group_type', models.CharField(max_length=5)),
                ('campaign_name', models.CharField(max_length=100)),
                ('buying_type', models.CharField(max_length=15)),
                ('ad_set_name', models.CharField(max_length=100)),
                ('ad_name', models.CharField(max_length=100)),
                ('link_type', models.CharField(max_length=7)),
                ('ga1', models.TextField()),
                ('ga2', models.TextField()),
                ('ga3', models.TextField()),
            ],
            options={
                'db_table': 'FBtest',
                'managed': False,
            },
        ),
    ]
