# Generated by Django 3.1.3 on 2020-11-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_v_fb_universal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbUniversalAd',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('ad_id', models.CharField(blank=True, max_length=25, null=True)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('cv', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('clientname', models.CharField(blank=True, db_column='ClientName', max_length=30, null=True)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=100, null=True)),
                ('accountname', models.CharField(blank=True, db_column='AccountName', max_length=100, null=True)),
                ('industrytype', models.CharField(blank=True, db_column='IndustryType', max_length=10, null=True)),
                ('stadatetime', models.DateTimeField(blank=True, db_column='StaDateTime', null=True)),
                ('group_type', models.CharField(blank=True, max_length=5, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=25, null=True)),
                ('campaign', models.CharField(blank=True, db_column='Campaign_Name', max_length=100, null=True)),
                ('ad_set_id', models.CharField(blank=True, max_length=25, null=True)),
                ('ad_set_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=100, null=True)),
                ('link_type', models.CharField(blank=True, max_length=7, null=True)),
                ('ga1', models.TextField(blank=True, null=True)),
                ('ga2', models.TextField(blank=True, null=True)),
                ('ga3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fb_universal_ad',
                'managed': False,
            },
        ),
    ]
